### ISSUE TITLE
Isathe 10x rescale still includes old asteroid size reduction multiplier

### ISSUE THREAD

**Issue by leganeski** [warriorsabe/Edge-Of-Eternity#25]
The section in the 10x rescale config file for Isathe still includes the lines `@radius *= 0.32` and `@geeASL *= 0.32`. This does not appear to be intentional given that the height maps are scaled by the full 10x, and that the corresponding `*= 0.64` lines were removed from the 2.56x config.

**Comment by warriorsabe** [comment]
Should now be fixed in 0.21.1, once I get the rest of the update ready
